// SEO maintenance for the Titanwall site. Run from the repo root:
//
//   node tools/seo.js                 refresh head tags, sitemap.xml, robots.txt
//   node tools/seo.js --site-url https://www.titanwall.com/
//                                     move every absolute URL to a new domain
//                                     (canonical links, share tags, sitemap,
//                                     form redirect, analytics domain, CNAME)
//
// Project pages are generated by build-projects.js; this script edits that
// template and regenerates them, so never hand-edit projects/*.html.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(__dirname, 'site-url.txt');
const rd = f => fs.readFileSync(path.join(ROOT, f), 'utf8');
const wr = (f, s) => fs.writeFileSync(path.join(ROOT, f), s);

let SITE = fs.readFileSync(CONFIG_PATH, 'utf8').trim();

// ------------------------------------------------------------ domain move
const flag = process.argv.indexOf('--site-url');
if (flag > -1) {
  let next = (process.argv[flag + 1] || '').trim();
  if (!/^https:\/\/[^/]+\//.test(next + (next.endsWith('/') ? '' : '/'))) throw new Error('usage: --site-url https://example.com/');
  if (!next.endsWith('/')) next += '/';
  const oldHost = new URL(SITE).hostname, newHost = new URL(next).hostname;
  const files = listFiles(['.html', '.js', '.xml', '.txt']).filter(f => !f.startsWith('tools/'));
  for (const f of files) {
    let s = rd(f);
    const before = s;
    s = s.split(SITE).join(next);
    if (f === 'js/site.js') s = s.replace(`domains: '${oldHost}'`, `domains: '${newHost}'`);
    if (s !== before) { wr(f, s); console.log('updated', f); }
  }
  // a custom domain needs a CNAME file; the github.io address does not
  if (!newHost.endsWith('.github.io')) { wr('CNAME', newHost + '\n'); console.log('wrote CNAME'); }
  fs.writeFileSync(CONFIG_PATH, next + '\n');
  SITE = next;
}

// ------------------------------------------------------------ pages
const OG_IMAGE = 'assets/og-share.jpg';
const pages = [
  { file: 'index.html', priority: '1.0' },
  { file: 'panel-system.html', priority: '0.9' },
  { file: 'why-titanwall.html', priority: '0.9' },
  { file: 'inside-the-building.html', priority: '0.8' },
  { file: 'privacy.html', priority: '0.2' },
];
const projectSlugs = [...rd('build-projects.js').matchAll(/slug:\s*'([^']+)'/g)].map(m => m[1]);

const headBlock = (urlPath, prefix, title, desc) => [
  '<!-- seo:start (maintained by tools/seo.js) -->',
  `<link rel="canonical" href="${SITE}${urlPath}">`,
  `<meta property="og:site_name" content="Titanwall MGO">`,
  `<meta property="og:locale" content="en_CA">`,
  `<meta property="og:url" content="${SITE}${urlPath}">`,
  title ? `<meta property="og:title" content="${title}">` : null,
  desc ? `<meta property="og:description" content="${desc}">` : null,
  `<meta property="og:image" content="${SITE}${OG_IMAGE}">`,
  `<meta property="og:image:width" content="1200">`,
  `<meta property="og:image:height" content="630">`,
  `<meta property="og:image:alt" content="Titanwall MGO: structure, insulation, barrier, one panel">`,
  `<meta name="twitter:image" content="${SITE}${OG_IMAGE}">`,
  `<meta name="theme-color" content="#0b0d10">`,
  `<link rel="apple-touch-icon" href="${prefix}assets/apple-touch-icon.png">`,
  '<!-- seo:end -->',
].filter(Boolean).join('\n');

function applyHead(src, block) {
  // drop any earlier block and any loose og:url, then insert after the favicon
  src = src.replace(/<!-- seo:start[\s\S]*?<!-- seo:end -->\n?/, '');
  src = src.replace(/<meta property="og:url"[^>]*>\n?/, '');
  const icon = src.match(/<link rel="icon"[^>]*>\n?/);
  if (!icon) throw new Error('no favicon line to anchor on');
  const at = icon.index + icon[0].length;
  return src.slice(0, at) + block + '\n' + src.slice(at);
}
const metaContent = (src, sel) => { const m = src.match(new RegExp(`<meta ${sel} content="([^"]*)"`)); return m ? m[1] : null; };

for (const p of pages) {
  let src = rd(p.file);
  const urlPath = p.file === 'index.html' ? '' : p.file;
  // pages that lack share title/description get them from <title> and description
  const title = metaContent(src, 'property="og:title"') ? null : (src.match(/<title>([^<]*)<\/title>/) || [])[1];
  const desc = metaContent(src, 'property="og:description"') ? null : metaContent(src, 'name="description"');
  src = applyHead(src, headBlock(urlPath, '', title, desc));
  wr(p.file, src);
}

// the generator: same block, with the URL path filled per project
let gen = rd('build-projects.js');
const genBlock = headBlock('projects/${p.slug}.html', '../', null, null).replace(/`/g, '\\`');
gen = gen.replace(/<!-- seo:start[\s\S]*?<!-- seo:end -->\n?/, '');
gen = gen.replace(/(<link rel="icon" href="\$\{FAVICON\}">\n)/, `$1${genBlock}\n`);
if (!gen.includes('seo:start')) throw new Error('generator favicon anchor not found');
wr('build-projects.js', gen);
execSync('node build-projects.js', { cwd: ROOT, stdio: 'ignore' });

// ------------------------------------------------------------ structured data (homepage)
let ix = rd('index.html');
const org = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'LocalBusiness',
      '@id': `${SITE}#business`,
      name: 'Titanwall MGO',
      alternateName: 'Titanwall Technologies',
      description: 'Manufacturer of MGO structural insulated panels: structure, insulation, air barrier and vapour barrier in one engineered panel, precision-manufactured in High River, Alberta.',
      url: SITE,
      logo: `${SITE}assets/logo-cube.png`,
      image: `${SITE}${OG_IMAGE}`,
      telephone: '+1-403-606-0855',
      email: 'marc@titanwall.com',
      foundingDate: '2005',
      address: { '@type': 'PostalAddress', addressLocality: 'High River', addressRegion: 'AB', addressCountry: 'CA' },
      areaServed: ['Canada', 'United States'],
      openingHoursSpecification: [{
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        opens: '07:00', closes: '17:00',
      }],
      sameAs: ['https://www.instagram.com/titanwalltechnologies/'],
    },
    { '@type': 'WebSite', '@id': `${SITE}#website`, url: SITE, name: 'Titanwall MGO', publisher: { '@id': `${SITE}#business` } },
  ],
};
const ld = `<!-- ld:start (maintained by tools/seo.js) -->\n<script type="application/ld+json">\n${JSON.stringify(org, null, 2)}\n</script>\n<!-- ld:end -->`;
ix = ix.replace(/<!-- ld:start[\s\S]*?<!-- ld:end -->\n?/, '');
ix = ix.replace('</head>', ld + '\n</head>');
wr('index.html', ix);

// ------------------------------------------------------------ sitemap + robots
const lastmod = (f) => {
  try { return execSync(`git log -1 --format=%cs -- "${f}"`, { cwd: ROOT }).toString().trim() || today(); }
  catch (e) { return today(); }
};
function today() { return new Date().toISOString().slice(0, 10); }
const entries = [
  ...pages.map(p => ({ loc: SITE + (p.file === 'index.html' ? '' : p.file), file: p.file, priority: p.priority })),
  ...projectSlugs.map(s => ({ loc: `${SITE}projects/${s}.html`, file: `projects/${s}.html`, priority: '0.7' })),
];
wr('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map(e => `  <url><loc>${e.loc}</loc><lastmod>${lastmod(e.file)}</lastmod><priority>${e.priority}</priority></url>`).join('\n')}
</urlset>
`);
wr('robots.txt', `User-agent: *
Allow: /
Disallow: /thanks.html
Disallow: /404.html

Sitemap: ${SITE}sitemap.xml
`);

console.log(`site url: ${SITE}`);
console.log(`head tags: ${pages.length} pages + ${projectSlugs.length} project pages; sitemap: ${entries.length} urls`);

function listFiles(exts) {
  const out = [];
  (function walk(dir) {
    for (const e of fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true })) {
      if (e.name.startsWith('.') || e.name === 'node_modules') continue;
      const rel = dir ? `${dir}/${e.name}` : e.name;
      if (e.isDirectory()) { if (e.name !== 'assets') walk(rel); }
      else if (exts.includes(path.extname(e.name))) out.push(rel);
    }
  })('');
  return out;
}
